[2024-12-02T19:33:04.443+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T19:33:04.488+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_hive_pipeline.consume_from_kafka manual__2024-12-02T19:32:20.279355+00:00 [queued]>
[2024-12-02T19:33:04.515+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_hive_pipeline.consume_from_kafka manual__2024-12-02T19:32:20.279355+00:00 [queued]>
[2024-12-02T19:33:04.518+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-02T19:33:04.610+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_from_kafka> on 2024-12-02 19:32:20.279355+00:00
[2024-12-02T19:33:04.627+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2339) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-02T19:33:04.630+0000] {standard_task_runner.py:72} INFO - Started process 2353 to run task
[2024-12-02T19:33:04.626+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_hive_pipeline', 'consume_from_kafka', 'manual__2024-12-02T19:32:20.279355+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/gestion_airflow.py', '--cfg-path', '/tmp/tmpwyxvx9yk']
[2024-12-02T19:33:04.632+0000] {standard_task_runner.py:105} INFO - Job 164: Subtask consume_from_kafka
[2024-12-02T19:33:04.798+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_hive_pipeline.consume_from_kafka manual__2024-12-02T19:32:20.279355+00:00 [running]> on host 45770b1a429e
[2024-12-02T19:33:05.000+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_hive_pipeline' AIRFLOW_CTX_TASK_ID='consume_from_kafka' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T19:32:20.279355+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T19:32:20.279355+00:00'
[2024-12-02T19:33:05.002+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T19:33:05.682+0000] {hive.py:475} INFO - USE `default`
[2024-12-02T19:33:06.052+0000] {hive.py:475} INFO - 
    CREATE TABLE IF NOT EXISTS sales (
        id STRING,
        invoice_id STRING,
        branch STRING,
        city STRING,
        customer_type STRING,
        gender STRING,
        product_line STRING,
        unit_price FLOAT,
        quantity INT,
        tax_5_percent FLOAT,
        total FLOAT,
        `date` STRING,
        time STRING,
        payment STRING,
        cogs FLOAT,
        gross_margin_percentage FLOAT,
        gross_income FLOAT,
        rating FLOAT
    ) STORED AS ORC
    
[2024-12-02T19:33:06.159+0000] {kafka_to_hive_with_redis.py:70} INFO - Subscribed to topic 'topic-batch'
[2024-12-02T19:34:10.837+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-02T19:34:10.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-02T19:34:10.843+0000] {process_utils.py:132} INFO - Sending 15 to group 2353. PIDs of all processes in the group: [2353]
[2024-12-02T19:34:10.844+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2353
[2024-12-02T19:34:11.165+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-02T19:34:11.257+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T19:34:11.301+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2353, status='terminated', exitcode=0, started='19:33:04') (2353) terminated with exit code 0
