[2024-12-09T16:20:15.486+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T16:20:15.557+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: dagappi.process_task_publish_dagappi manual__2024-12-09T15:54:24.839362+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-12-09T16:20:15.593+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
